### ISSUE TITLE
Expo error ViewPropTypes.style on Release mode

### ISSUE THREAD

**Issue by leoafarias** [jfilter/react-native-onboarding-swiper#101]
Hi,

While running the expo app in release mode. I am getting an error
`TypeError: undefined is not an object (evaluating 'k.ViewPropTypes.style')`

Which means the app gets a blank screen and doesn't open. The issue points at this package, sorry if I cannot get a more detailed error, but on production, a lot of the logs are being supressed.

**Comment by sdavid501** [comment]
I'm getting similar error:
containerStyles: ViewPropTypes.style

**Comment by ranjani23** [comment]
+1, I ran into this error as well. looks like  there are other search hits with ViewPropTypes being deprecated as well. https://github.com/reactrondev/react-native-web-swiper/issues/41

**Comment by abuhumayed** [comment]
I tried on Expo too, I'm new to react-native but deffo won't be trying this again on Expo, it resulted in me having to try to re-install node and clone and initialise my project on a new one .

**Comment by AW42** [comment]
> I tried on Expo too, I'm new to react-native but deffo won't be trying this again on Expo, it resulted in me having to try to re-install node and clone and initialise my project on a new one .

What's the solution then? it was working fine then after few days I come across this error and can't find its solution

**Comment by jonsmirl** [comment]
This component is not compatible with Expo until the ViewPropTypes issues are resolved.

**Comment by jayrap24** [comment]
Yeah same here, getting that error and I have Expo. Anyone know of good alternatives?

**Comment by abuhumayed** [comment]
I managed to get mine working on expo in the end, not near my laptop now but lookup getting async storage for expo and use the necessary import lined for it. I'll have a look once able to

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by abuhumayed** [comment]
I'm pretty sure I used to get the package

expo install react-native-onboarding-swiper







Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jfilter** [comment]
This was fixed. However, React Native for Web is currently not working. https://github.com/jfilter/react-native-onboarding-swiper/issues/83
