### ISSUE TITLE
How I can  move to next index by use of my custom btn.

### ISSUE THREAD

**Issue by ahmedishtiaq9777** [jfilter/react-native-onboarding-swiper#106]

**Comment by ariisrael** [comment]
Make sure you are passing in `props`:

```javascript
const Next = ({ ... props }) => (
  <TouchableOpacity {...props}>
    <Text>Next</Text>
  </TouchableOpacity>
)
```

**Comment by saymondamasio** [comment]
I have is same problem

**Comment by jfilter** [comment]
I'm not sure if I understand the problem, but you are able to control the pages imperatively: https://github.com/jfilter/react-native-onboarding-swiper#controlling-the-pages-imperatively
