### ISSUE TITLE
How do I implement conditional rendering inside?

### ISSUE THREAD

**Issue by jiaheyi-maggie** [jfilter/react-native-onboarding-swiper#107]
I have a list of data and a boolean field with a checklist, and I want to render one screen for each selected element base on their boolean value. Is there a way to do this in the swiper? I tried making a component and did the logic inside the component and wrapped it around as an image but it doesn't work.

**Comment by jfilter** [comment]
While I haven't tried it, you should be able to store `pages` in a state and update the state when the user completes the checklist. If anybody comes across this and has problems, please let me know.
