### ISSUE TITLE
Button Margin Right or Margin End Not working

### ISSUE THREAD

**Issue by harshalone** [jfilter/react-native-onboarding-swiper#108]
I have added a simple Done button and want to give it a margin 30 but its not working

My Code:

```
<Button style={styles(colors).done}
          title={'Done'} 
          buttonStyle={{
            marginEnd: 30,
          }}
          containerViewStyle={{
            marginEnd: 30,
          }}    
        /> 
```
followed the example code

**Comment by jfilter** [comment]
I don't know what's wrong, but I'm pretty sure there is another way to achieve the desired layout. :)
