### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by mohamamddev** [jfilter/react-native-onboarding-swiper#109]
Hi, I have this problem!
How can i fix that?

TypeError: Cannot read property 'style' of undefined

  49 | Page.propTypes = {
  50 |   isLight: PropTypes.bool.isRequired,
  51 |   image: PropTypes.element.isRequired,
> 52 |   containerStyles: ViewPropTypes.style,
  53 |   imageContainerStyles: ViewPropTypes.style,
  54 |   title: PropTypes.oneOfType([PropTypes.string, PropTypes.element]).isRequired,
  55 |   subtitle: PropTypes.oneOfType([PropTypes.string, PropTypes.element])

**Comment by Jonak-Adipta-Kalita** [comment]
I also go the same error in the WEB!!

**Comment by Jonak-Adipta-Kalita** [comment]
Nope, Not yet :(

**Comment by LeandroFontellas** [comment]
Same problem here :/

**Comment by dgillier** [comment]
ViewPropTypes' is not supported in 'react-native-web' v12.0 onwards...

**Comment by jfilter** [comment]
This was fixed. However, React Native for Web is currently not working. https://github.com/jfilter/react-native-onboarding-swiper/issues/83
