### ISSUE TITLE
Special animation / fade in for done button

### ISSUE THREAD

**Issue by jfilter** [jfilter/react-native-onboarding-swiper#11]

**Comment by hadesownage** [comment]
+1

**Comment by wafisher** [comment]
Is there any way to disable this effect? I don't love this effect: it can be unclear where the next/done button is if you're looking for it immediately as the screen loads.

**Comment by jfilter** [comment]
You can use your own button component: https://github.com/jfilter/react-native-onboarding-swiper#custom-components-properties

**Comment by wafisher** [comment]
Oh good idea, thanks! Didn’t think of that.
________________________________
