### ISSUE TITLE
please add the onclick handler of each onboarding item

### ISSUE THREAD

**Issue by maheshmuttinti** [jfilter/react-native-onboarding-swiper#112]
can u please add the onclick/onpress event handlers for each onboarding item to navigate to other screens or popup coming when onboarding item clicked

**Comment by jfilter** [comment]
You can provide your own component for the image and set the title and subtitle to a blank string. In your component, you can add your own logic. See https://github.com/jfilter/react-native-onboarding-swiper/issues/99.
