### ISSUE TITLE
BottomBar Position

### ISSUE THREAD

**Issue by vaikunth-gloify** [jfilter/react-native-onboarding-swiper#114]
How to change the BottomBar position of Skip and Next buttons ?
whether we can change or it's fixed ?

<img width="238" alt="Screenshot 2021-09-01 at 12 31 16 PM" src="https://user-images.githubusercontent.com/75018972/131626714-cb6d39cf-3889-42e6-ba51-8375c588a7f9.png">

**Comment by jotilohana** [comment]
@vaikunth-gloify  did you solve this? I also want to change background color

**Comment by vaikunth-gloify** [comment]
> @vaikunth-gloify did you solve this? I also want to change background color

No @jotilohana , I tried but time is not there for me. So, I changed the library for swiper

**Comment by martinapereyra** [comment]
How did you change the color of the buttons from white to black?

**Comment by jotilohana** [comment]
You can customize the buttons using "NextButtonComponent" and "SkipButtonComponent "

**Comment by jeremiahjoyjoseph** [comment]
You can use

bottomBarHeight (optional): a number for the height of the bottom bar. Defaults to 60.
bottomBarColor (optional): backgroundColor of the bottom bar. Defaults to transparent.
bottomBarHighlight (optional): a bool flag indicating whether the bottom bar should be highlighted. Defaults to true.

bottomBarHeight will change the footerBackground color, and setting the bottomBarHighlight to false will remove the shade.

You can hide the skip button by setting showSkip={false}.

**Comment by jfilter** [comment]
You can customize the components: https://github.com/jfilter/react-native-onboarding-swiper#custom-components-properties
