### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by ishqDehlvi** [jfilter/react-native-onboarding-swiper#115]
Module../node_modules/react-native-onboarding-swiper/src/Page.js
http://localhost:19006/static/js/bundle.js:46656:94
  46653 | Page.propTypes = {
  46654 |   isLight: prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.bool.isRequired,
  46655 |   image: prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.element.isRequired,
> 46656 |   containerStyles: react_native_web_dist_index__WEBPACK_IMPORTED_MODULE_3__["ViewPropTypes"].style,
        |                                                                                              ^  46657 |   imageContainerStyles: react_native_web_dist_index__WEBPACK_IMPORTED_MODULE_3__["ViewPropTypes"].style,
  46658 |   title: prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.oneOfType([prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.string, prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.element]).isRequired,
  46659 |   subtitle: prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.oneOfType([prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.string, prop_types__WEBPACK_IMPORTED_MODULE_4___default.a.element]).isRequired,

**Comment by jfilter** [comment]
This was fixed. However, React Native for Web is currently not working. https://github.com/jfilter/react-native-onboarding-swiper/issues/83
