### ISSUE TITLE
Grey background strip on round iPhone displays

### ISSUE THREAD

**Issue by t-kaufmann** [jfilter/react-native-onboarding-swiper#116]
On iPhones with a round display, the bottom of the Onboarding Swiper stays grey. Neither changing the default color of the app-theme nor setting `bottomBarColor={"white"}` do change that.

![image](https://user-images.githubusercontent.com/34220946/136853459-621a5113-3a74-4f79-b09c-675f0aaa6381.png)

**Comment by jfilter** [comment]
What happens when you set `bottomBarHighlight` to `false`?

**Comment by ASchwad** [comment]
This component uses a `SafeAreaView` for [rendering its contents](https://github.com/jfilter/react-native-onboarding-swiper/blob/d732783681fae546deb5c97b73cde918cbb45644/src/index.js#L207).

You can encapsulate your `Onboarding` component with another `View` to set the color in the bottom stripe which is kept as a distance from the SafeAreaView.

Example:
```
// Flex to let the container grow over full screen.
<View style={{flex: 1, backgroundColor: 'white'}}>
      <Onboarding
        // color of bottom tab controls container
        bottomBarColor='white'
        // for other colors you should set bottomBarHighlight this to false
        // otherwise the color will be applied with [0.1 opacity](https://github.com/jfilter/react-native-onboarding-swiper/blob/d732783681fae546deb5c97b73cde918cbb45644/src/index.js#L314)
        bottomBarHighlight={false}
       ...
       />
</View>
```

**Comment by bhubr** [comment]
@jfilter I hadn't read the whole thread, so I fumbled with the bottom bar-related props, and setting `bottomBarHighlight` to `false` indeed did the trick!
