### ISSUE TITLE
permanently delete skip button and how to change footer background

### ISSUE THREAD

**Issue by jotilohana** [jfilter/react-native-onboarding-swiper#117]

**Comment by jeremiahjoyjoseph** [comment]
You can use 

bottomBarHeight (optional): a number for the height of the bottom bar. Defaults to 60.
bottomBarColor (optional): backgroundColor of the bottom bar. Defaults to transparent.
bottomBarHighlight (optional): a bool flag indicating whether the bottom bar should be highlighted. Defaults to true.

bottomBarColor will change the footerBackground color. 

You can hide the skip button by setting showSkip={false}.

**Comment by jfilter** [comment]
Please consult the documentation. https://github.com/jfilter/react-native-onboarding-swiper/blob/master/README.md
