### ISSUE TITLE
Warning: Failed child context type: Invalid child context `virtualizedCell.cellKey` of type `number` supplied to `CellRenderer`, expected `string`.

### ISSUE THREAD

**Issue by pjay79** [jfilter/react-native-onboarding-swiper#12]
![simulator screen shot - iphone x - 2018-02-26 at 18 41 23](https://user-images.githubusercontent.com/14052885/36660774-7514f4fe-1b2d-11e8-9b08-0f10e8c50d6a.png)
![simulator screen shot - iphone x - 2018-02-26 at 18 41 55](https://user-images.githubusercontent.com/14052885/36660776-7561f286-1b2d-11e8-9a75-fc7be363acf2.png)

I am getting this error. Any ideas why this is happening?

React v16.2
React-native v0.53
React-native-onborading-swiper v0.4.1.1

**Comment by pjay79** [comment]
Ok, modifiying keyExtractor seems to have done the trick in the index.js file seems fix this.

react-native-onboarding-swiper/src/index.js
keyExtractor = (item, index) => index.toString();

**Comment by jfilter** [comment]
Thanks for reporting and fixing. Will take a look into this later today.

**Comment by pjay79** [comment]
No probs :)

If possible could you please check out this thread on stackoverflow? I am having trouble implementing this library...

https://stackoverflow.com/questions/49009217/react-native-setstate-unmounted-or-mounting-component <https://stackoverflow.com/questions/49009217/react-native-setstate-unmounted-or-mounting-component>

Many thanks,

Praveen.

**Comment by jfilter** [comment]
Thanks for your PR. Fixed in #13.
