### ISSUE TITLE
 imageContainerStyles not working for me

### ISSUE THREAD

**Issue by butri71** [jfilter/react-native-onboarding-swiper#120]
Hi,

I'm trying to overrides some default value set by imageContainer by using imageContainerStyles as per your explanation.

`subTitleStyles` is working but `imageContainerStyles` has no effect whatsoever, no matter what I define inside.

`
pages={[
            {
                backgroundColor: '#a6e4d0',
                image: <Image source={require('../assets/images/onboarding/screen1.png')} />,
                title: t('onboardingTitle1'),
                subtitle: t('onboardingText1'),   
                subTitleStyles: { marginBottom: 20 },
                imageContainerStyles: { borderWidth:1, paddingBottom: 20 }
            },
`
Thanks

**Comment by jfilter** [comment]
Hey, you need to set `imageContainerStyles` like this on the component itself:

```<Onboarding pages=xx imageContainerStyles=xx />```
