### ISSUE TITLE
Example of How To Make Onboarding Screen Load Only Once

### ISSUE THREAD

**Issue by AnatuGreen** [jfilter/react-native-onboarding-swiper#122]
Hi,

Apologies if this seems noobish, can we have an example of how to make this load only on the first app opening after installation and never again on subsequent openings unless the user clears the app storage or reinstalls? Just like in a real whole app?

**Comment by jfilter** [comment]
Hey, 

this has to be done outside of this component. If you need on-boarding, display this component. If you want to skip on-boarding, don't render it. Use onDone and onSkip to persist an appropriate flag.
