### ISSUE TITLE
Setting bottomBarHighlight to false causes a warning

### ISSUE THREAD

**Issue by Temzasse** [jfilter/react-native-onboarding-swiper#14]
Hi! 👋and thanks for this super useful component 🙂

I noticed this one small thingy when setting `bottomBarHighlight={false}` it cause a warning in the Pagination component:

<img width="295" alt="screen shot 2018-03-09 at 14 09 37" src="https://user-images.githubusercontent.com/6152032/37207081-ff8f16c2-23a3-11e8-85ab-7bef94b28f49.png">

I guess it is because of this line: https://github.com/jfilter/react-native-onboarding-swiper/blob/master/src/index.js#L145

**Comment by jfilter** [comment]
Thanks for reporting. ;)
