### ISSUE TITLE
Page: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by EliasGxA** [jfilter/react-native-onboarding-swiper#149]

**Comment by front100** [comment]
i have the same issue.

**Comment by vishnu-krishna** [comment]
i also have the same issue.. any solution?

**Comment by matiaswastaken** [comment]
Can we please get @julekgwa's pull request approved and merged to fix this?

**Comment by robinokwanma** [comment]
Any update on the merge?

**Comment by asfour75** [comment]
Any updtes on this ?

**Comment by JuniusBBD** [comment]
@jfilter please have a look at this issue and review the PR to fix it.

**Comment by nelsonsilvadev** [comment]
@jfilter

**Comment by leikoilja** [comment]
@jfilter

**Comment by JuniusBBD** [comment]
Alternative maintained library https://github.com/julekgwa/react-native-app-onboard

**Comment by leikoilja** [comment]
> Alternative maintained library https://github.com/julekgwa/react-native-app-onboard

thanks for the link to @julekgwa's fork, i ll take a look of using that instead in a meanwhile

**Comment by AlexMachin1997** [comment]
Whilst the fork is appreciated, it would be much preferred if the developers or even community could get a pull request together to remove warning/error.

**Comment by jfilter** [comment]
Fixed in v1.3.0. Thanks for the notifications. :)
