### ISSUE TITLE
Allow any React component as a label

### ISSUE THREAD

**Issue by Temzasse** [jfilter/react-native-onboarding-swiper#15]
Hi again 👋 

I would like to use react-intl and it's FormattedMessage as a `nextLabel` but at the moment it only accepts a string as a label (well things work but there is a warning).

I see you are setting the label simply as `{nextLabel}` inside the *NextButton* so basically it can be any React component, right?

Thanks in advance!

**Comment by jfilter** [comment]
Thanks for reporting. ;)
