### ISSUE TITLE
Custom Page component

### ISSUE THREAD

**Issue by vikas5914** [jfilter/react-native-onboarding-swiper#21]
HI, 

I want to use a custom component for the pages. 

is there any way to do that?

**Comment by jfilter** [comment]
You should be able to style your page as you need. You can give custom components for to `image`, `subtitle` and `title`. You can also tweak/remove some styles with `imageContainerStyles`.

**Comment by jfilter** [comment]
You can to this with the current version:

  <Onboarding
    pages={[
      {
        backgroundColor: '#fff',
        image: <View><Image source={require('./images/circle.png')} /><Image source={require('./images/circle.png')} /></View>,
        title: 'Onboarding',
        subtitle: 'Done with React Native Onboarding Swiper',
      },
    ]}
/>

You can give whatever you want to the image prop.
