### ISSUE TITLE
Pressing skip and making the Onboarding skip to the last page of it

### ISSUE THREAD

**Issue by Strafer14** [jfilter/react-native-onboarding-swiper#27]
Hi, I've been wondering if it's possible to force the onboarding component to go to the last page of the onboarding when pressed Skip. I can't find it anywhere in the examples.

**Comment by Zohaibmalikdev** [comment]
Same here.

**Comment by Strafer14** [comment]
Hey @Zohaibmalikdev, I found that you can create a ref in the library and manually pull the next() function from within, I am planning to write my own onboarding library though based on the ScrollView component that will have this feature easily, let's stay in touch.

**Comment by jfilter** [comment]
This wasn't possible until now so I added `skipToPage`. It lets you skip to the specified page.
