### ISSUE TITLE
imageContainerStyles Issues.

### ISSUE THREAD

**Issue by MichaelChuba** [jfilter/react-native-onboarding-swiper#29]
(imageContainerStyles) property is not overrides. How do i change the margin or padding Bottom to different value?

**Comment by Yasernova** [comment]
i'm having the same issue

**Comment by jfilter** [comment]
Yeah, it was not properly implemented. Thanks for reporting.

**Comment by MichaelChuba** [comment]
Ok please, i will be waiting.

**Comment by okumujustine** [comment]
was this fixed

**Comment by jfilter** [comment]
Yes

**Comment by moe12572** [comment]
How do I use the imageStyleContainer? Can you give me an example code?
