### ISSUE TITLE
Customizable Dots, Skip & Next Button ?

### ISSUE THREAD

**Issue by deadcoder0904** [jfilter/react-native-onboarding-swiper#3]
Is there anyway to make it customizable or are u planning to implement it ?

**Comment by jfilter** [comment]
Yeah, why not. Do you think it's sufficient to have a prop for dot size/color or shit it be entirely replaceable?

**Comment by deadcoder0904** [comment]
Yeah, I wanted it 2 days ago, but there is [another popular library](https://github.com/leecade/react-native-swiper) that I used to do it.

But if this is completely customizable, it would be way awesome bcz this library has the sweetest & simplest API

**Comment by jfilter** [comment]
Done, a new update will be shipped soon.

**Comment by deadcoder0904** [comment]
Thanks man

**Comment by mohamedadel1994825** [comment]
> Yeah, I wanted it 2 days ago, but there is [another popular library](https://github.com/leecade/react-native-swiper) that I used to do it.
> 
> But if this is completely customizable, it would be way awesome bcz this library has the sweetest & simplest API

this library attached has an issue with rtl .
