### ISSUE TITLE
StatusBar being changed even when controlStatusBar is set to null

### ISSUE THREAD

**Issue by TimonSotiropoulos** [jfilter/react-native-onboarding-swiper#34]
Hello,

Nice library (firstly). 

A bug when I set the controlStatusBar bool to false, it still makes the statusbar revert to default when the Onboarding screen is closed. This should not happen.

Can be easily fixed by updating the code in the Pagination component.

Cheers

**Comment by jfilter** [comment]
Thanks for reporting. Fixed it in v0.7.1.
