### ISSUE TITLE
Get current page number

### ISSUE THREAD

**Issue by janvdt** [jfilter/react-native-onboarding-swiper#35]
Hi,

I would like to ask permissions like location,camera, etc... on the different onboarding steps. Is it possible to retrieve the current page number as a callback when going to the next screen?

**Comment by jfilter** [comment]
You can give a custom component to the `subtitle` and do whatever you want there. Check this example: https://github.com/jfilter/react-native-onboarding-swiper/blob/master/examples/WithCTA.js

I don't like the idea of asking for permission when going to the next page. Better add a button, i.e., `Enable Notifications` and then ask for permission on click.
