### ISSUE TITLE
Headers style

### ISSUE THREAD

**Issue by IsharaHansaka** [jfilter/react-native-onboarding-swiper#36]
How to change title and subtitle styles?(ex: fontSizes, colors) Couldn't find any prop for that in the doc.

**Comment by MeganGilligan1** [comment]
@IsharaHansaka did you manage to work this out?

**Comment by lowewenzel** [comment]
I was able to customize the header title and subtitle by passing in my own components to the `title` and `subtitle` properties per page. Ex:

```
pages={[
  {
    backgroundColor: '#F6F9FC',
    image: <Image style={styles.firstImage} source={require('./logo.png')} />,
    title: <Text style={{fontWeight: '300', fontSize: 20}}>Test Header</Text>,
    subtitle: 'Solve sleep in your commute'
  }, ...
```

**Comment by jfilter** [comment]
In 0.8.0, there are new props to adjust the title's styles. (https://github.com/jfilter/react-native-onboarding-swiper/pull/38)
