### ISSUE TITLE
Add Current Page Property

### ISSUE THREAD

**Issue by Ingibjorg** [jfilter/react-native-onboarding-swiper#41]
For tracking purposes, I would like to know on which page the user is on when they click the skip button. Can you make the currentPage property available somehow? 

I've tried achieving this information by overriding the onViewableItemsChanged FlatList property but that causes my app to run out of memory.

Do you have any better way of achieving this?

**Comment by jfilter** [comment]
There is a new callback to get a page index on page change. See https://github.com/jfilter/react-native-onboarding-swiper/pull/40. Let me know if it works for you.

**Comment by Ingibjorg** [comment]
Thanks @jfilter, that works for me!
