### ISSUE TITLE
Dynamic title and subtitle color based on background color

### ISSUE THREAD

**Issue by danoszz** [jfilter/react-native-onboarding-swiper#44]
First of all, thank you for creating the swiper component. It works like a charm. I've been trying to adjust the color of the title and subtitle of the pages according to the isLight function, but couldn't work it out.

## Current behavior

The text of the `pages` dynamically changes color, between black and white, based on the background color. I try to make the text custom colored, but it only worked at the Skip button component taken from the [CustomButtons.js](https://github.com/jfilter/react-native-onboarding-swiper/blob/master/examples/CustomButtons.js) example.

```
const getBackgroundColor = (isLight: boolean) =>
  isLight ? customColors.cyanDark : customColors.white;

const Skip = ({ isLight, ...props }) => {
  return (
    <View style={style.skipButton}>
      <Button
        title={"Skip"}
        color={getBackgroundColor(isLight)}
        onPress={() => navigate("Main")}
      />
    </View>
  );
};

```

## Nice to have

An option where you can enter a custom 'dark' and 'light' color for the title and subtitle. 

## For now

What would be best practise to change the colors dynamicly?

**Comment by jfilter** [comment]
You can always pass in your `<Component/>` for the title and subtitles like [this](https://github.com/jfilter/react-native-onboarding-swiper/blob/master/examples/WithCTA.js).

But with the just released version 0.10.0, you should also be able to modify the title and subtitle's style on a page level like this:

```js

<Onboarding
  pages={[
    {
      backgroundColor: '#fff',
      image: <Image source={require('./images/circle.png')} />,
      title: 'Onboarding',
      subtitle: 'Done with React Native Onboarding Swiper',
      titleStyles: {color: 'red'}
    },
    ...
  ]}
/>

```

Let me know if it works for you.

**Comment by danoszz** [comment]
This works perfectly! I've used the `titleStyles` on a page level. Also, I saw it was added to the documentation and examples. Thanks for your swift reply.

**Comment by danoszz** [comment]
When passing an object to prop type `titleStyles` it throws an error. Before the `0.10.0` update it did work. Trying to find a solution and do a PR. 

```
<Onboarding
  titleStyles={[
    textStyles.title1,
    {
      paddingHorizontal: 10,
      color: 'blue',
    },
  ]}
  pages={[
    (...)
  ]}
/>;
```

**Comment by eazzyLEE** [comment]
Hello guys, my android status bar has been totally balck since i integrated the react-native-onboarding-swiper. Does anyone have any idea on how to correct this?
![screenshot_20181203-141029](https://user-images.githubusercontent.com/29065790/49381785-054b6080-f715-11e8-8d68-e04a310d7e7b.png)

**Comment by eazzyLEE** [comment]
@jfilter

**Comment by jfilter** [comment]
@danoszz: Coming back to your problem. This should work:
```js
<Onboarding
  titleStyles={{
      paddingHorizontal: 10,
      color: 'blue',
      ...textStyles.title1
    }}
```
You can only pass one object and not an array of objects.
