### ISSUE TITLE
Programmatically control paging

### ISSUE THREAD

**Issue by RWOverdijk** [jfilter/react-native-onboarding-swiper#51]
Hey, cool module. I've been playing with it a bit and it does work well, when used the way it was intended to.

But I don't want to use it the way it was intended to, because I'm a rebel. :D 

I want to not show the pagination component, and handle that myself. Is there any way to accomplish that? I checked out the code but it doesn't look like it.

**Comment by RWOverdijk** [comment]
ref + this.theRef.goNext();

**Comment by cmaronchick** [comment]
Hi @RWOverdijk can you provide a little more detail (or an example) on what ref + this.theRef.goNext() means? I tried it but couldn't get it to work. Thanks!

**Comment by aal89** [comment]
@cmaronchick What he meant was something like this (taking from the CTA example):

```
<Onboarding
    showDone={false}
    onSkip={() => Alert.alert('Skipped')}
    ref={onboarding => {
      this.onboarding = onboarding;
    }}
   ...
```

Then anywhere call this to programmatically go to the next page:
`this.onboarding.goNext();`

**Comment by cmaronchick** [comment]
Thanks @aal89!

**Comment by YossiSaadi** [comment]
Hey,
Anyway to do it with functional component w/ hooks?
I'm trying to do 
`const boarding = useRef();
...... 
<Onboarding ... ref={boarding} />`
But no success in accessing the boarding.current.something()

**Comment by YossiSaadi** [comment]
Hey,
Anyway to do it with functional component w/ hooks?
I'm trying to do
`const boarding = useRef(); ...... <Onboarding ... ref={boarding} />`
But no success in accessing the `boarding.current.something()`

**Comment by Allyday** [comment]
I currently only see a method to goNext. Is there one to go back, or to jump to a certain page?

**Comment by YossiSaadi** [comment]
> I currently only see a method to goNext. Is there one to go back, or to jump to a certain page?

I'm guessing you can make usage in skipToPage, with saving the state of the current page.

**Comment by Allyday** [comment]
> > I currently only see a method to goNext. Is there one to go back, or to jump to a certain page?
> 
> I'm guessing you can make usage in skipToPage, with saving the state of the current page.

Yes, but that's only called when you press the built-in `Skip` button. In my particular use case, I want to have a custom `Back` button in the place of the current `Skip` button, and fire a goBack() method whenever it's clicked.
