### ISSUE TITLE
calls 'onDone' right away

### ISSUE THREAD

**Issue by zachtepper** [jfilter/react-native-onboarding-swiper#54]
I am testing the 'onDone' property by logging to console: `console.log('Finished Onboarding')`. I realized when the Onboard component renders, it logs to the console right away and does not wait for me to click the Done button. How do I fix this so that it will log to console after I've clicked done?

**Comment by jfilter** [comment]
```js
onDone={() => console.log('done')}
```

This calls the function on done.
