### ISSUE TITLE
Persistance

### ISSUE THREAD

**Issue by maniart** [jfilter/react-native-onboarding-swiper#56]
Hey there, thank you for your wonderful work.
Is there any mechanism currently in place that let's the user skip on-boarding after the first use? Or will on-boarding render every time the app is opened?

Thanks!

**Comment by jfilter** [comment]
This has to be done outside of this component. If you need on-boarding, display this component. If you want to skip on-boarding, don't render it. Use `onDone` and `onSkip` to persist an appropriate flag.
