### ISSUE TITLE
Transition to the next screen super slow

### ISSUE THREAD

**Issue by GavBaros** [jfilter/react-native-onboarding-swiper#58]
I tried implementing this in both a current project and a fresh react-native one, but the transition to the next screen is still slow. 

I am using version 1.1.0. 

It is like the gif examples in your README, but 5-10x slower. What might be the issue?

EDIT: I'm using iPhone X for this. I have noticed that on iPhone 7 or models before iPhone X , the library works perfectly.

**Comment by GavBaros** [comment]
Note that this happens when PRESSING the next button, dragging into the next screen looks fast.

**Comment by jfilter** [comment]
You are not talking about the animation, right?

**Comment by GavBaros** [comment]
its actually the animation. When swiping with my cursor on the simulator, its fast. But when I click next, its ultra slow.

**Comment by jfilter** [comment]
I can't reproduce it. Can you produce a minimal runable example?

**Comment by GavBaros** [comment]
I can only replicate locally unfortunately, using iOS simulator. I have tried another library, still same effect. My guess is this lag will not be an issue in a prod environment (non-simulator).

**Comment by jfilter** [comment]
Okay, feel free to re-open this issue if you experience this issue in production.
