### ISSUE TITLE
Possible to add new component to replace bottom bar?

### ISSUE THREAD

**Issue by GavBaros** [jfilter/react-native-onboarding-swiper#59]
I am looking to have an exact layout like in the attached picture:
![example](https://user-images.githubusercontent.com/30755017/58381681-f2289780-7fb7-11e9-8e4a-38e439b883cb.JPG)

Is this library sufficient to achieve that exact design? 

So there is a bold Header, a picture in the middle, then a paragraph and the normal skip + dots + next buttons. 
In the last screen, the bottom bar is replaced completely with a Login and Signup button. 

I was wondering if its possible to achieve this with this library? I'm not sure if the current props allow for this to happen.

Thanks!

**Comment by jeffinhk** [comment]
seems like a very old issue but I would still like to ask you whether you have solved this or not. May I get some advice from your memory?
