### ISSUE TITLE
Adding events with each page view

### ISSUE THREAD

**Issue by cmaronchick** [jfilter/react-native-onboarding-swiper#62]
Is it possible to call a function with each page view in order to view traffic through the flow of the onboarding?

I'm using Amplitude with Expo, if that helps, and just need to log events with when the user navigates between pages. Thanks!

**Comment by jfilter** [comment]
You can render custom components as, i.e., title and could call `componentDidMount`.

https://github.com/jfilter/react-native-onboarding-swiper#required-properties

**Comment by cmaronchick** [comment]
Hi @jfilter Thank you for the response. Actually, your "pageIndexCallback" method works just fine, so I used that. One less thing to worry about. Beautiful job!
