### ISSUE TITLE
Integrate next button into a page?

### ISSUE THREAD

**Issue by cmaronchick** [jfilter/react-native-onboarding-swiper#63]
Hi, a main part of my app experience is entering info into a couple of Inputs and hitting a submit button. I am showing the UI in one of the pages, but I cannot figure out if I can use the submit button to go to the next screen.

Is that possible? Thanks!

**Comment by jfilter** [comment]
See this issue, should be possible: https://github.com/jfilter/react-native-onboarding-swiper/issues/51
