### ISSUE TITLE
Export TextButton & SymbolButton

### ISSUE THREAD

**Issue by mhuggins** [jfilter/react-native-onboarding-swiper#65]
I don't like the way the done button works (would rather use the word "Done" without any fade animation).  I simply want to mimic the behavior of the "Skip" button for when the user's done.

The `DoneButtonComponent` prop is perfect for allowing this behavior, but it feels like I'm reinventing the wheel to mimic the existing text button behavior.  I'm pretty much just copying out the `TextButton` and `NextButton` code, which also means that I'll need to be aware of changes to those internal components whenever I upgrade the dependency in my app.

I'd like to propose exporting those components such that users can easily create buttons matching the style embedded in this package.  Thanks!

**Comment by jfilter** [comment]
There are no plans to change the internal structure of this package. I don't do a lot RN anymore. I will maintain this package but not develop it any further. So I think c&p is fine. ;)

But yeah, I agree. It should be so complicated to adapt the styles.

**Comment by mhuggins** [comment]
That's too bad.  Thanks anyway!
