### ISSUE TITLE
Onboarding in Android Device is skipped to the end when KeyPress

### ISSUE THREAD

**Issue by pckz** [jfilter/react-native-onboarding-swiper#66]
Hello

I'm using this library to implement an onboarding mixed with a wizard form.
The first page is for presentation, and the others are to ask things about the user: the name, phone, email.

I'm using the parameter image to insert a <TextInput  and works fine in iOS

The problem is in Android, when I change the value of the TextInput the onboarding go directly to the last page.

![ezgif-4-eb19e37a8c7f](https://user-images.githubusercontent.com/1050628/61900276-4930e700-aeeb-11e9-8bfd-47e5242e4960.gif)

Note: I know the image param is for <Image :( but works with other component

**Comment by jfilter** [comment]
Without any code example, I cannot replicate your problem.
