### ISSUE TITLE
Go to next slide programmatically

### ISSUE THREAD

**Issue by pckz** [jfilter/react-native-onboarding-swiper#68]
Hello,
I'm developing a wizard form using this awesome lib.
I'm using the image component to put a TextInput and works well. When someone press the next button in the keyboard, needs to be transported to the next slide, so, here is my question:

¿How can I go to the next slide programmatically?
What function I have to call to be transported to the next slide of this onboarding

Thanks!

**Comment by jfilter** [comment]
see https://github.com/jfilter/react-native-onboarding-swiper/issues/51
