### ISSUE TITLE
Invariant Violation: Changing ViewabilityConfig on the fly is not supported

### ISSUE THREAD

**Issue by DanCarl857** [jfilter/react-native-onboarding-swiper#7]
While using this component in RN 0.50.4, I get the red screen below:

![screen shot 2017-11-26 at 10 41 39 am](https://user-images.githubusercontent.com/9010142/33238861-6c01b13e-d296-11e7-82a8-6b06c2502d7e.png)

**Comment by jfilter** [comment]
Thanks for reporting.
