### ISSUE TITLE
Weird page rendering

### ISSUE THREAD

**Issue by vijaysharm** [jfilter/react-native-onboarding-swiper#70]
There's some weird rendering between pages. This happens when i swipe to the next page. The last page does have subtitle which is a bit longer, but i assumed it would just word wrap. See images below. Any help would be appreciated.

![rendering](https://user-images.githubusercontent.com/1824094/63526857-166c1580-c4ce-11e9-8920-b98512922568.png)

![rendering1](https://user-images.githubusercontent.com/1824094/63526928-33084d80-c4ce-11e9-8071-031911b1e008.png)

**Comment by Ghiffary** [comment]
try to check your margin or padding? hope that the problem
