### ISSUE TITLE
Hide next on one screen until a user has performed an action

### ISSUE THREAD

**Issue by kirkryan** [jfilter/react-native-onboarding-swiper#71]
Hi,

We love the onboarding swiper! Halfway through our onboarding process, we prompt the user for their name. We would like to hide the skip button whilst this takes place until a user has entered the appropriate information.

Is it possible to hide the next button on a single page? We tried toggling the showNext prop but it doesn't seem to affect the layout once the onboarding sequence has been loaded.

Thanks in advance!

KR

**Comment by jfilter** [comment]
You can provide your own Skip component via `SkipButtonComponent` do the logic there:
