### ISSUE TITLE
How to import images from API?

### ISSUE THREAD

**Issue by sal-g** [jfilter/react-native-onboarding-swiper#72]
I've made an array from my API JSON object like the array required for the screens using array.map 

```
screens.map(function(item) {
    return {
      backgroundColor: '#FFFFFF',
      image: (<Image source={{uri: `${item['image']}`}} />),
      title: item.title,
      subtitle: item.subtitle
    };
  })
```

However since the images are image components, the array becomes really messy 

What can I do

**Comment by jfilter** [comment]
I don't understand the problem.
