### ISSUE TITLE
Unable to resolve "./components/Panel" from "node_modules\rn-swipeable-panel\index.js"

### ISSUE THREAD

**Issue by Sbrao666** [jfilter/react-native-onboarding-swiper#82]
I just install  panel using command  `$ npm install rn-swipeable-panel --save`
after that i import package like `import SwipeablePanel from 'rn-swipeable-panel';` 

and i got error when refresh
this is the error on cmd  ` Unable to resolve "./components/Panel" from "node_modules\rn-swipeable-panel\index.js"`
 and on mobile device i got error  as shown in screenshot
![Screenshot_20200621-111322_Expo](https://user-images.githubusercontent.com/47715376/85217634-9134e400-b3b0-11ea-941c-424a71cc72af.jpg)
![Screenshot_20200621-111336_Expo](https://user-images.githubusercontent.com/47715376/85217636-998d1f00-b3b0-11ea-8c45-8a47896bedea.jpg)
![Screenshot_20200621-111329_Expo](https://user-images.githubusercontent.com/47715376/85217637-9c880f80-b3b0-11ea-9e4d-8c6aba81ebf2.jpg)

**Comment by jfilter** [comment]
Are you sure this is the correct repo for you issue? Looks like a different component to me.
