### ISSUE TITLE
Doesn't auto resize on orientation change

### ISSUE THREAD

**Issue by mario-subotic** [jfilter/react-native-onboarding-swiper#9]
Hi, 

I'm using `react-native-onboarding-swiper` `v ^0.3.1` in my Expo CRNA app and when I test on my iPad on landscape the pages are stitched together with the width of the device in portrait mode. This means it works well in portrait mode, but on landscape it's unaligned. 

![img_0070](https://user-images.githubusercontent.com/20719836/35310633-4a49923e-00ed-11e8-94bf-0a09ce018964.PNG)
![img_0071](https://user-images.githubusercontent.com/20719836/35310637-5177d250-00ed-11e8-9bd0-a66b0fe21f61.PNG)

Any advice how I can adjust/fix this?

**Comment by jfilter** [comment]
This is currently not supported. I will fix this in the version which will be released in ~2 weeks.

**Comment by jfilter** [comment]
done
