### ISSUE TITLE
How to Change StatusBar Color on Each Screen?

### ISSUE THREAD

**Issue by Sanan4li** [jfilter/react-native-onboarding-swiper#97]
Hi,
I don't know how I can change statusbar color so that it matches the screen color. If there is any option I am missing please share.

**Comment by sagarshakya** [comment]
You can set the `translucent` property of the `<Statusbar />` to `true`. 
```
<Statusbar translucent={true} />
```

**Comment by jfilter** [comment]
Thanks @sagarshakya for resolving the issue.
